### ISSUE TITLE
v52 is always disabled after reboot

### ISSUE THREAD

**Issue by li-yifei** [Magisk-Modules-Repo/active_edge_system_mod#3]
# ENV
Magisk 20.1
Pixel 4 XL on QD1A.190821.007.A3
Module version: v52
Other modules: Riru core, Riru storage redirect module.

Thanks for your update for Pixel 4 XL. But the magisk module was always disabled after installation and every reboot.

**Comment by jtothe4n** [comment]
That's because the november update dropped yesterday and the bootloop protection script disabled the module. You need to wait a few more hours till v53 drops

**Comment by li-yifei** [comment]
Oh I saw your replies on XDA. Waiting for the update.:kissing_heart:
